In [ ]:
!ls /content/drive/MyDrive/DSAI_Prj-1/data/image

origin.7z.001  origin.7z.003  origin.7z.005  origin.7z.007
origin.7z.002  origin.7z.004  origin.7z.006  origin.7z.008


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!7za -y x "/content/drive/MyDrive/DSAI_Prj-1/data/image/origin.7z.*"


7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs Intel(R) Xeon(R) CPU @ 2.20GHz (406F0),ASM,AES-NI)

Scanning the drive for archives:
  0M Scan /content/drive/MyDrive/DSAI_Prj-1/data/image/                                                       8 files, 8113576419 bytes (7738 MiB)
  0%    
Extracting archive: /content/drive/MyDrive/DSAI_Prj-1/data/image/origin.7z.001
--
Path = /content/drive/MyDrive/DSAI_Prj-1/data/image/origin.7z.001
Type = Split
Physical Size = 1048576000
Volumes = 8
Total Physical Size = 8113576419
----
Path = origin.7z
Size = 8113576419
--
Path = origin.7z
Type = 7z
Physical Size = 8113576419
Headers Size = 863607
Method = LZMA:25
Solid = +
Blocks = 2

  0%      0% - origin/afraid_African_214.jpg            

In [ ]:
!cp -r ./origin "/content/drive/MyDrive/DSAI_Prj-1"

In [4]:
label_file_path=r"/content/drive/MyDrive/DSAI_Prj-1/data/label/label.lst"
images_folder_path=r"/content/drive/MyDrive/DSAI_Prj-1/origin"

In [5]:
from numpy import split
import pandas as pd
df_info = pd.read_csv(label_file_path, sep=" ",header=None)
col_names="image_name face_id_in_image face_box_top face_box_left face_box_right face_box_bottom face_box_confidence expression_label".split()
df_info.columns = col_names

df_info.head()

image_name  face_id_in_image  face_box_top  face_box_left  \
0  angry_actor_104.jpg                 0            28            113   
1  angry_actor_109.jpg                 0            31            157   
2  angry_actor_120.jpg                 1            53             53   
3   angry_actor_13.jpg                 0            77             51   
4  angry_actor_132.jpg                 0            95             31   

   face_box_right  face_box_bottom  face_box_confidence  expression_label  
0             226              141              22.9362                 0  
1             345              219              50.3056                 0  
2             372              372              13.9434                 2  
3             362              388              85.8104                 3  
4             412              476              82.3948                 0

In [6]:
df_sel=df_info[df_info.face_box_confidence>45]

# New Section

In [7]:
df_sel

image_name  face_id_in_image  face_box_top  \
1                 angry_actor_109.jpg                 0            31   
3                  angry_actor_13.jpg                 0            77   
4                 angry_actor_132.jpg                 0            95   
5                 angry_actor_137.jpg                 0            93   
9                 angry_actor_150.jpg                 0            56   
...                               ...               ...           ...   
91786    surprised_expression_409.jpg                 0            80   
91787  expressionless_husband_673.jpg                 0            48   
91789    surprised_expression_381.jpg                 0            51   
91790    surprised_expression_395.jpg                 0            27   
91792    surprised_expression_394.jpg                 0            47   

       face_box_left  face_box_right  face_box_bottom  face_box_confidence  \
1                157             345              219              50.3056   
3                 51             362              388              85.8104   
4                 31             412              476              82.3948   
5                468             842              467              88.9519   
9                263             376              169              81.8792   
...              ...             ...              ...                  ...   
91786             46             184              218              63.8069   
91787            194             388              242              82.2975   
91789             61             117              107              91.6307   
91790             95             258              190              96.2861   
91792             38             152              161              77.7758   

       expression_label  
1                     0  
3                     3  
4                     0  
5                     0  
9                     0  
...                 ...  
91786                 5  
91787                 4  
91789                 5  
91790                 5  
91792                 5  

[51856 rows x 8 columns]

In [8]:
df_sel.shape

(51856, 8)

In [48]:
import cv2
import os
x=[]
y=[]
for i, row in df_sel.iterrows():
  img_name=row["image_name"]
  x1 = row["face_box_left"]
  y1=row["face_box_top"]
  x2=row["face_box_right"]
  y2=row["face_box_bottom"]
  label=row["expression_label"]
  img_path=os.path.join(images_folder_path,img_name)

  image = cv2.imread(img_path)

  #croping
  if image is not None:
        cropped=image[y1:y2, x1:x2]
        face = cv2.resize(cropped, (64, 64))
        if face is not None:
          x.append(face)
          y.append(label)


In [59]:
import numpy as np
X = np.array(x)
Y = np.array(y)

In [60]:
X

array([[[[ 31,  48,  60],
         [ 30,  46,  59],
         [ 38,  51,  65],
         ...,
         [ 87,  95, 108],
         [ 94, 103, 115],
         [ 40,  49,  59]],

        [[ 33,  50,  62],
         [ 28,  41,  55],
         [ 36,  47,  61],
         ...,
         [ 89,  96, 111],
         [ 92, 100, 113],
         [ 70,  78,  90]],

        [[ 27,  40,  54],
         [ 22,  33,  47],
         [ 32,  43,  57],
         ...,
         [ 87,  94, 109],
         [ 90,  97, 112],
         [ 91,  99, 112]],

        ...,

        [[ 84,  89, 120],
         [ 83,  89, 120],
         [ 86,  92, 121],
         ...,
         [ 45,  61,  78],
         [ 38,  55,  71],
         [ 38,  54,  71]],

        [[ 86,  91, 122],
         [ 85,  90, 121],
         [ 88,  94, 123],
         ...,
         [ 35,  51,  68],
         [ 33,  49,  66],
         [ 31,  47,  64]],

        [[ 93,  98, 129],
         [ 87,  92, 123],
         [ 88,  94, 123],
         ...,
         [ 36,  52,  69],
        

In [61]:
Y

array([1, 3, 3, ..., 1, 6, 6])

In [126]:
len(X)

5866

In [63]:
len(Y)

1706

In [64]:
X.shape

(1706, 64, 64, 3)

In [65]:
Y.shape

(1706,)

In [66]:
normalized_X = X / 255.0

In [67]:
normalized_X

array([[[[0.12156863, 0.18823529, 0.23529412],
         [0.11764706, 0.18039216, 0.23137255],
         [0.14901961, 0.2       , 0.25490196],
         ...,
         [0.34117647, 0.37254902, 0.42352941],
         [0.36862745, 0.40392157, 0.45098039],
         [0.15686275, 0.19215686, 0.23137255]],

        [[0.12941176, 0.19607843, 0.24313725],
         [0.10980392, 0.16078431, 0.21568627],
         [0.14117647, 0.18431373, 0.23921569],
         ...,
         [0.34901961, 0.37647059, 0.43529412],
         [0.36078431, 0.39215686, 0.44313725],
         [0.2745098 , 0.30588235, 0.35294118]],

        [[0.10588235, 0.15686275, 0.21176471],
         [0.08627451, 0.12941176, 0.18431373],
         [0.1254902 , 0.16862745, 0.22352941],
         ...,
         [0.34117647, 0.36862745, 0.42745098],
         [0.35294118, 0.38039216, 0.43921569],
         [0.35686275, 0.38823529, 0.43921569]],

        ...,

        [[0.32941176, 0.34901961, 0.47058824],
         [0.3254902 , 0.34901961, 0.47058824]

In [129]:
normalized_X.shape

(1706, 64, 64, 3)

In [132]:
X_new=normalized_X.reshape((-1,64*64*3))
X_new.shape

(1706, 12288)

In [133]:
X_new

array([[0.12156863, 0.18823529, 0.23529412, ..., 0.12941176, 0.19215686,
        0.25882353],
       [0.36470588, 0.50196078, 0.49803922, ..., 0.        , 0.        ,
        0.        ],
       [0.23921569, 0.38431373, 0.48627451, ..., 0.01176471, 0.01960784,
        0.0627451 ],
       ...,
       [0.99607843, 0.99607843, 0.99607843, ..., 1.        , 1.        ,
        1.        ],
       [0.23529412, 0.23921569, 0.29803922, ..., 0.72941176, 0.4745098 ,
        0.30196078],
       [0.08627451, 0.11764706, 0.23137255, ..., 0.56470588, 0.60784314,
        0.78039216]])

In [134]:
X_new.shape

(1706, 12288)

In [135]:
import pandas as pd
pd.Series(Y).value_counts()

3    838
6    552
5    188
1     58
2     30
4     26
0     14
dtype: int64

In [136]:
X_new.shape

(1706, 12288)

In [137]:
Y.shape

(1706,)

In [138]:
from imblearn.over_sampling import SMOTE
sampler = SMOTE()
X_smote,Y_smote=sampler.fit_resample(X_new, Y)

In [139]:
pd.Series(Y_smote).value_counts()

1    838
3    838
6    838
4    838
0    838
5    838
2    838
dtype: int64

In [140]:
X=X_smote.reshape(-1,64,64,3)

In [141]:
X

array([[[[0.12156863, 0.18823529, 0.23529412],
         [0.11764706, 0.18039216, 0.23137255],
         [0.14901961, 0.2       , 0.25490196],
         ...,
         [0.34117647, 0.37254902, 0.42352941],
         [0.36862745, 0.40392157, 0.45098039],
         [0.15686275, 0.19215686, 0.23137255]],

        [[0.12941176, 0.19607843, 0.24313725],
         [0.10980392, 0.16078431, 0.21568627],
         [0.14117647, 0.18431373, 0.23921569],
         ...,
         [0.34901961, 0.37647059, 0.43529412],
         [0.36078431, 0.39215686, 0.44313725],
         [0.2745098 , 0.30588235, 0.35294118]],

        [[0.10588235, 0.15686275, 0.21176471],
         [0.08627451, 0.12941176, 0.18431373],
         [0.1254902 , 0.16862745, 0.22352941],
         ...,
         [0.34117647, 0.36862745, 0.42745098],
         [0.35294118, 0.38039216, 0.43921569],
         [0.35686275, 0.38823529, 0.43921569]],

        ...,

        [[0.32941176, 0.34901961, 0.47058824],
         [0.3254902 , 0.34901961, 0.47058824]

In [142]:
import numpy as np
from keras.utils import to_categorical
onehot_encoded_y = to_categorical(Y)

# Display the one-hot encoded representation
print(onehot_encoded_y)


[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [146]:
import numpy as np
from sklearn.model_selection import train_test_split

# Assuming 'x' is your input features and 'y' is the corresponding target labels
# Replace these with your actual data arrays

# Split the data into training (70%), testing (15%), and validation (15%) sets
X_train, X_temp, Y_train, Y_temp = train_test_split(normalized_X, onehot_encoded_y, test_size=0.3, random_state=42)
X_val, X_test, Y_val, Y_test = train_test_split(X_temp, Y_temp, test_size=0.5, random_state=42)

# Display the sizes of each split
print("Training set size:", len(X_train))
print("Validation set size:", len(X_val))
print("Testing set size:", len(X_test))

Training set size: 1194
Validation set size: 256
Testing set size: 256


In [147]:
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

# Assuming 'x_train' is your training data and 'y_train' are the corresponding labels
# Replace these with your actual training data and labels

# Create an ImageDataGenerator for data augmentation
datagen = ImageDataGenerator(
    rotation_range=20,      # Random rotation
    width_shift_range=0.2,  # Random horizontal shift
    height_shift_range=0.2, # Random vertical shift
    shear_range=0.2,        # Random shear
    zoom_range=0.2,         # Random zoom
    horizontal_flip=True,   # Random horizontal flip
    fill_mode='nearest'     # Fill mode for newly created pixels
)

# Fit the ImageDataGenerator on the training data
datagen.fit(X_train)

# Generate augmented data batches
augmented_data_generator = datagen.flow(X_train, Y_train, batch_size=32)



In [148]:
X_train

array([[[[0.02352941, 0.04313725, 0.09803922],
         [0.01960784, 0.04313725, 0.10196078],
         [0.03921569, 0.07058824, 0.1254902 ],
         ...,
         [0.00784314, 0.00392157, 0.04705882],
         [0.03529412, 0.        , 0.05490196],
         [0.03137255, 0.        , 0.05882353]],

        [[0.03137255, 0.05490196, 0.10980392],
         [0.00784314, 0.03137255, 0.08627451],
         [0.04313725, 0.07058824, 0.1254902 ],
         ...,
         [0.01176471, 0.        , 0.04705882],
         [0.07058824, 0.01176471, 0.08235294],
         [0.08627451, 0.00784314, 0.09803922]],

        [[0.01176471, 0.03921569, 0.10588235],
         [0.01568627, 0.03921569, 0.10588235],
         [0.04313725, 0.07058824, 0.1372549 ],
         ...,
         [0.01176471, 0.        , 0.04705882],
         [0.03137255, 0.        , 0.05490196],
         [0.03921569, 0.        , 0.0627451 ]],

        ...,

        [[0.14117647, 0.17647059, 0.27058824],
         [0.18039216, 0.20784314, 0.30980392]

In [149]:

Y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [150]:
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Assuming 'x_train' and 'y_train' are your training data and labels, respectively
# Replace these with your actual training data and labels

# Create the CNN model
model = Sequential()

# Add the first convolutional layer
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(64,64,3)))

# Add the first max-pooling layer
model.add(MaxPooling2D(pool_size=(2, 2)))

# Add the second convolutional layer
model.add(Conv2D(64, (3, 3), activation='relu'))

# Add the second max-pooling layer
model.add(MaxPooling2D(pool_size=(2, 2)))

# Flatten the output from the previous layer
model.add(Flatten())

# Add the first fully connected (dense) layer
model.add(Dense(128, activation='relu'))

# Add the output layer with appropriate number of classes and activation function
num_classes = 7
model.add(Dense(num_classes, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history=model.fit(X_train, Y_train, epochs=100, batch_size=32, validation_data=(X_val, Y_val))


Epoch 1/100
38/38 [==============================] - 2s 13ms/step - loss: 1.3216 - accuracy: 0.4615 - val_loss: 1.2343 - val_accuracy: 0.5195
Epoch 2/100
38/38 [==============================] - 0s 7ms/step - loss: 1.2200 - accuracy: 0.5109 - val_loss: 1.1637 - val_accuracy: 0.5625
Epoch 3/100
38/38 [==============================] - 0s 7ms/step - loss: 1.1207 - accuracy: 0.5704 - val_loss: 1.1193 - val_accuracy: 0.6133
Epoch 4/100
38/38 [==============================] - 0s 7ms/step - loss: 0.9854 - accuracy: 0.6256 - val_loss: 1.0814 - val_accuracy: 0.6055
Epoch 5/100
38/38 [==============================] - 0s 7ms/step - loss: 0.8538 - accuracy: 0.6734 - val_loss: 1.1106 - val_accuracy: 0.6055
Epoch 6/100
38/38 [==============================] - 0s 7ms/step - loss: 0.7692 - accuracy: 0.7178 - val_loss: 1.1287 - val_accuracy: 0.6328
Epoch 7/100
38/38 [==============================] - 0s 7ms/step - loss: 0.6133 - accuracy: 0.7647 - val_loss: 1.1872 - val_accuracy: 0.6289
Epoch 8/100


In [82]:
#oversampling
#limitation take 2d data